const Data = [
  {
    id: 1,
    img: '/images/red_1.jpg',
    alt: 'Gambar 1',
    name: 'red_1',
    category: 'Red',
  },
  {
    id: 2,
    img: '/images/Yellow_1.jpg',
    alt: 'Gambar 2',
    name: 'yellow_1',
    category: 'Yellow',
  },
  {
      id: 3,
      img: '/images/green_1.jpg',
      alt: 'Gambar 3',
      name: 'green_3',
      category: 'Green',
    },
    {
      id: 4,
      img: '/images/blue_1.jpg',
      alt: 'Gambar 4',
      name: 'blue_1',
      category: 'Blue',
    },
    {
      id: 5,
      img: '/images/yellow_2.jpg',
      alt: 'Gambar 5',
      name: 'blue_1',
      category: 'Yellow',
    },
    {
      id: 6,
      img: '/images/blue_2.jpg',
      alt: 'Gambar 2',
      name: 'blue_2',
      category: 'Blue',
    },
    {
      id: 7,
      img: '/images/red_2.jpg',
      alt: 'Gambar 3',
      name: 'red_2',
      category: 'Red',
    },
    {
      id: 8,
      img: '/images/green_2.jpg',
      alt: 'Gambar 4',
      name: 'blue_4',
      category: 'Green',
    },
    {
      id: 9,
      img: '/images/green_3.jpg',
      alt: 'Gambar 3',
      name: 'red_3',
      category: 'Green',
    },
    {
      id: 10,
      img: '/images/red_3.jpg',
      alt: 'Gambar 3',
      name: 'red_3',
      category: 'Red',
    },
    {
      id: 11,
      img: '/images/blue_3.jpg',
      alt: 'Gambar 3',
      name: 'red_3',
      category: 'Blue',
    },
    {
      id: 12,
      img: '/images/yellow_4.jpg',
      alt: 'Gambar 3',
      name: 'red_3',
      category: 'Yellow',
    },
    {
      id: 13,
      img: '/images/blue_4.jpg',
      alt: 'Gambar 3',
      name: 'red_3',
      category: 'Blue',
    },
    {
      id: 14,
      img: '/images/yellow_5.jpg',
      alt: 'Gambar 3',
      name: 'red_3',
      category: 'Yellow',
    },
    {
      id: 15,
      img: '/images/green_4.jpg',
      alt: 'Gambar 3',
      name: 'red_3',
      category: 'Green',
    },
    {
      id: 16,
      img: '/images/red_4.jpg',
      alt: 'Gambar 3',
      name: 'red_4',
      category: 'Red',
    },
];

export default Data;
